version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: dockerfile
    image: api:dev
    container_name: api
    restart: always
    volumes:
      - ./:/usr/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
