name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v2

      - name: Run Test
        run: vr test
        env:
          SECRET: TestSecretValue
          DB_USERNAME: testmanager
          DB_PASSWORD: testpassword
          COLLECTION: Test
